spring:
    application:
        name: demo
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: ${DB_URL:jdbc:mysql://localhost:3306/account?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:12345678}
    sql:
        init:
            encoding: UTF-8

bot:
    token: ${BOT_TOKEN:isatoken}

jwt:
    secret: ${JWT_SECRET_KEY:your_jwt_secret_key}

wallet:
    api:
        url: ${WALLET_API_URL:https://backend-dev.worldwidewallet.app}  
        key: ${WALLET_API_KEY:631aca4f-79c8-427e-8132-ecfd75286569}  
